---
# tasks file for prac_4

- name: Make a directory with new SELinux context
  ansible.builtin.file:
    name: "{{ var_dir }}"
    state: directory
    owner: "{{ var_owner }}"
    group: "{{ var_group }}"
    mode: "{{ var_mode }}"
    setype: "{{ var_setype }}"


