---
# tasks file for prac_3
- name: Write line to /etc/fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: present
    line: "{{ var_lineinfile }}"
- name: Reboot system
  ansible.builtin.reboot:

